symbol = {
    'alpha': 'α',
    'beta': 'β',
    'gamma': 'γ',
    'lambda': 'λ',
    'plus': '+',
    'add': '+',
    'subtract': '-',
    'minus': '-',
    'into': '*',
    'multiply': 'X',
    'divide': '/',
    'by': '/',
    'percentage': '%',
    'mod': '%',
    'theta': 'θ',
    'integration': '∫',
    'derivative': '∂',
    'differentiation': '∂',
    'equal to': '=',
    'equals to': '=',
    'equas': '=',
    'limit': 'lim',
    'squared': '^2',
    'cubed': '^3',
    'square root': '√',
    'root': '√',
    'cube root': '∛',
    'power': '^',
    'phi': 'φ',
    'mixed fraction': '¾',
    'pi': 'π',
    'sigma': 'σ',
    'delta': 'δ',
    'epsilon': 'ε',
    'mu': 'μ',
    'nu': 'ν',
    'omicron': 'ο',
    'rho': 'ρ',
    'tau': 'τ',
    'upsilon': 'υ',
    'psi': 'ψ',
    'omega': 'ω',
    'greater than': '>',
    'less than': '<',
    'gtet': '≥',
    'ltet': '≤',
    'not equal to': '≠',
    'infinity': '∞',
    'integral': '∫',
    'partial': '∂',
    'degree': '°',
    'angle': '∠',
    'perpendicular': '⊥',
    'parallel': '∥',
    'बीटा': 'β',
    'गामा': 'γ',
    'लैम्ब्डा': 'λ',
    'प्लस': '+',
    'जोड़ें': '+',
    'घटाएं': '-',
    'माइनस': '-',
    'गुणा': '*',
    'मल्टीप्लाई': 'X',
    'डिवाइड': '/',
    'द्वारा': '/',
    'प्रतिशत': '%',
    'मॉड': '%',
    'थीटा': 'θ',
    'इंटीग्रेशन': '∫',
    'डेरिवेटिव': '∂',
    'अवकलन': '∂',
    'बराबर है': '=',
    'बराबर है': '=',
    'बराबर': '=',
    'सीमा': 'lim',
    'वर्ग': '^2',
    'घन': '^3',
    'वर्गमूल': '√',
    'घनमूल': '∛',
    'पावर': '^',
    'फी': 'φ',
    'मिश्रित भिन्न': '¾',
    'पाई': 'π',
    'सिग्मा': 'σ',
    'डेल्टा': 'δ',
    'एप्सिलॉन': 'ε',
    'म्यू': 'μ',
    'न्यू': 'ν',
    'ओमिक्रॉन': 'ο',
    'रो': 'ρ',
    'टाउ': 'τ',
    'अप्सिलॉन': 'υ',
    'प्सी': 'ψ',
    'ओमेगा': 'ω',
    'से अधिक': '>',
    'से कम': '<',
    'से अधिक या बराबर': '≥',
    'से कम या बराबर': '≤',
    'समान नहीं': '≠',
    'अनंत': '∞',
    'इंटीग्रल': '∫',
    'आंशिक': '∂',
    'डिग्री': '°',
    'कोण': '∠',
    'लंब': '⊥',
    'समानांतर': '∥',
    'bêta': 'β',
    'gamma': 'γ',
    'lambda': 'λ',
    'plus': '+',
    'ajouter': '+',
    'soustraire': '-',
    'moins': '-',
    'fois': '*',
    'multiplier': 'X',
    'diviser': '/',
    'par': '/',
    'pourcentage': '%',
    'mod': '%',
    'theta': 'θ',
    'intégration': '∫',
    'dérivée': '∂',
    'différenciation': '∂',
    'égal à': '=',
    'égal à': '=',
    'égal': '=',
    'limite': 'lim',
    'carré': '^2',
    'cubé': '^3',
    'racine carrée': '√',
    'racine cubique': '∛',
    'puissance': '^',
    'phi': 'φ',
    'fraction mixte': '¾',
    'pi': 'π',
    'sigma': 'σ',
    'delta': 'δ',
    'epsilon': 'ε',
    'mu': 'μ',
    'nu': 'ν',
    'omicron': 'ο',
    'rho': 'ρ',
    'tau': 'τ',
    'upsilon': 'υ',
    'psi': 'ψ',
    'oméga': 'ω',
    'plus grand que': '>',
    'moins que': '<',
    'plus grand ou égal': '≥',
    'moins ou égal': '≤',
    'pas égal à': '≠',
    'infini': '∞',
    'intégrale': '∫',
    'partiel': '∂',
    'degré': '°',
    'angle': '∠',
    'perpendiculaire': '⊥',
    'parallèle': '∥',
    'beta': 'β',
    'gamma': 'γ',
    'lambda': 'λ',
    'plus': '+',
    'hinzufügen': '+',
    'subtrahieren': '-',
    'minus': '-',
    'mal': '*',
    'multiplizieren': 'X',
    'teilen': '/',
    'durch': '/',
    'prozent': '%',
    'mod': '%',
    'theta': 'θ',
    'integration': '∫',
    'ableitung': '∂',
    'differenzierung': '∂',
    'gleich': '=',
    'gleich': '=',
    'gleich': '=',
    'grenze': 'lim',
    'quadratisch': '^2',
    'kubisch': '^3',
    'quadratische wurzel': '√',
    'kubische wurzel': '∛',
    'potenz': '^',
    'phi': 'φ',
    'gemischter bruch': '¾',
    'pi': 'π',
    'sigma': 'σ',
    'delta': 'δ',
    'epsilon': 'ε',
    'mu': 'μ',
    'nu': 'ν',
    'omicron': 'ο',
    'rho': 'ρ',
    'tau': 'τ',
    'upsilon': 'υ',
    'psi': 'ψ',
    'omega': 'ω',
    'größer als': '>',
    'kleiner als': '<',
    'größer oder gleich': '≥',
    'kleiner oder gleich': '≤',
    'nicht gleich': '≠',
    'unendlich': '∞',
    'integral': '∫',
    'partiell': '∂',
    'grad': '°',
    'winkel': '∠',
    'senkrecht': '⊥',
    'parallel': '∥',
    'beta': 'β',
    'gamma': 'γ',
    'lambda': 'λ',
    'más': '+',
    'agregar': '+',
    'restar': '-',
    'menos': '-',
    'por': '*',
    'multiplicar': 'X',
    'dividir': '/',
    'por': '/',
    'porcentaje': '%',
    'mod': '%',
    'theta': 'θ',
    'integración': '∫',
    'derivada': '∂',
    'diferenciación': '∂',
    'igual a': '=',
    'igual a': '=',
    'igual': '=',
    'límite': 'lim',
    'cuadrado': '^2',
    'cubo': '^3',
    'raíz cuadrada': '√',
    'raíz cúbica': '∛',
    'potencia': '^',
    'phi': 'φ',
    'fracción mixta': '¾',
    'pi': 'π',
    'sigma': 'σ',
    'delta': 'δ',
    'epsilon': 'ε',
    'mu': 'μ',
    'nu': 'ν',
    'ómicron': 'ο',
    'rho': 'ρ',
    'tau': 'τ',
    'upsilon': 'υ',
    'psi': 'ψ',
    'omega': 'ω',
    'mayor que': '>',
    'menor que': '<',
    'mayor o igual a': '≥',
    'menor o igual a': '≤',
    'no igual a': '≠',
    'infinito': '∞',
    'integral': '∫',
    'parcial': '∂',
    'grado': '°',
    'ángulo': '∠',
    'perpendicular': '⊥',
    'paralelo': '∥',
    'ಬೀಟಾ': 'β',
    'ಗಾಮಾ': 'γ',
    'ಲ್ಯಾಂಬ್ಡಾ': 'λ',
    'ಪ್ಲಸ್': '+',
    'ಸೇರಿಸಿ': '+',
    'ಕಡಿತಿರಿ': '-',
    'ಮೈನಸ್': '-',
    'ಗುಣಿಸಿ': '*',
    'ಮಲ್ಟಿಪ್ಲೈ': 'X',
    'ವಿಭಜಿಸು': '/',
    'ಮೂಲಕ': '/',
    'ಶೇಕಡಾ': '%',
    'ಮಾಡ್': '%',
    'ಥೀಟಾ': 'θ',
    'ಸಮಾಕಲನ': '∫',
    'ಅವಕಲನ': '∂',
    'ಅವಕಲನ': '∂',
    'ಸಮಾನ': '=',
    'ಸಮಾನ': '=',
    'ಸಮಾನ': '=',
    'ಮಿತಿ': 'lim',
    'ವರ್ಗ': '^2',
    'ಘನ': '^3',
    'ವರ್ಗಮೂಲ': '√',
    'ಘನಮೂಲ': '∛',
    'ಪವರ್': '^',
    'ಫೈ': 'φ',
    'ಮಿಶ್ರಭಿನ್ನ': '¾',
    'ಪೈ': 'π',
    'ಸಿಗ್ಮಾ': 'σ',
    'ಡೆಲ್ಟಾ': 'δ',
    'ಎಪ್ಸಿಲಾನ್': 'ε',
    'ಮ್ಯೂ': 'μ',
    'ನ್ಯೂ': 'ν',
    'ಒಮಿಕ್ರಾನ್': 'ο',
    'ರೋ': 'ρ',
    'ಟೌ': 'τ',
    'ಅಪ್ಸಿಲಾನ್': 'υ',
    'ಪ್ಸಿ': 'ψ',
    'ಓಮೇಗಾ': 'ω',
    'ಹೆಚ್ಚು': '>',
    'ಕಡಿಮೆ': '<',
    'ಹೆಚ್ಚು ಅಥವಾ ಸಮ': '≥',
    'ಕಡಿಮೆ ಅಥವಾ ಸಮ': '≤',
    'ಸಮಾನವಲ್ಲ': '≠',
    'ಅನಂತ': '∞',
    'ಸಮಾಕಲನ': '∫',
    'ಭಾಗಶಃ': '∂',
    'ಅಂಗುಲ': '°',
    'ಕೋನ': '∠',
    'ಲಂಬ': '⊥',
    'ಸಮಾನಾಂತರ': '∥',



}

def get():
    return symbol.copy()
